package cz.cvut.fel.omo.smarthome.logs;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * In-memory log of events emitted by devices/sensors and handled by the system.
 *
 * <p>Stores {@link EventEntry} objects generated by {@code SystemEventListener}.
 * This log is later used by {@code EventReportGenerator} to produce a human-readable report.</p>
 */
public class EventLog {

    /** Internal list of event records in insertion order. */
    private final List<EventEntry> entries = new ArrayList<>();

    /**
     * Adds a new event entry to the log.
     *
     * @param e event entry to add
     */
    public void add(EventEntry e) {
        entries.add(e);
    }

    /**
     * Returns an unmodifiable view of all logged event entries.
     *
     * @return read-only list of entries
     */
    public List<EventEntry> getEntries() {
        return Collections.unmodifiableList(entries);
    }

    /**
     * Clears the log (used when re-initializing the simulation context).
     */
    public void clear() {
        entries.clear();
    }
}
